dist: trusty
language: php
php:
  - '7.1'
  - '7.2'
install: php build/composer.phar install --no-interaction

addons:
  sonarcloud:
    organization: "simovative"
    #token:
      #secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - php build/phpunit.phar --configuration tests/phpunit.xml
  - sonar-scanner

after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php build/coveralls.phar -v  -c .coveralls.yaml
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
