language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
install: php build/composer.phar install --no-interaction

addons:
	sonarcloud:

	organization: "sonarcloud_organization_key"
	# the key of the org you chose at step
	#3 
	token: 
	secure: ********* 
	# encrypted value of your token 
	script: 
	# other script steps might be done before running the actual analysis
	- sonar-scanner

script: php build/phpunit.phar --configuration tests/phpunit.xml

after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php build/coveralls.phar -v  -c .coveralls.yaml
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
